name: Secure Supply Chain CI

on:
  push:
    branches: [ main ]

permissions:
  id-token: write  # Needed for OIDC-based identity
  contents: read   # To clone your code in the workflow

jobs:
  build-sign-sbom:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build image
      run: docker build -t ghcr.io/${{ github.repository }}:latest .

    - name: Install Cosign
      uses: sigstore/cosign-installer@main

    - name: Install Syft
      uses: anchore/sbom-action/download-syft@v0.14.3

    - name: Generate SBOM
      run: syft dir:. -o spdx-json > sbom.json

    - name: Keyless sign Docker image
      env:
        COSIGN_EXPERIMENTAL: 1
      run: cosign sign ghcr.io/${{ github.repository }}:latest

    - name: Keyless sign SBOM
      env:
        COSIGN_EXPERIMENTAL: 1
      run: |
        cosign sign-blob --output-signature sbom.sig --output-certificate sbom.crt sbom.json

